export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 260,
      brand: " Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 10,
    },
    {
      _id: "2",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 350,
      brand: " Nike",
      rating: 4.2,
      numReviews: 5,
      countInStock: 2,
    },
    {
      _id: "3",
      name: "Best Pants",
      category: "Pants",
      image: "/images/d3.jpg",
      price: 470,
      brand: " Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 60,
    },
    {
      _id: "4",
      name: "Best Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 710,
      brand: " Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 16,
    },
    {
      _id: "5",
      name: "Best Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 170,
      brand: " Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
    },
    {
      _id: "6",
      name: "Best Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 170,
      brand: " Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 1,
    },
  ],
};